#!/usr/bin/python
# -*- coding: UTF-8 -*-
# vim: expandtab sw=4 ts=4 sts=4:
'''
Creates folders on IMAP.
'''
__author__ = 'Michal Čihař'
__email__ = 'michal@cihar.com'
__license__ = '''
Copyright (c) 2003 - 2007 Michal Čihař

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published by
the Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
'''
import sys
import getopt
import IMAPUtils

class ListIMAP(IMAPUtils.IMAPUtils):
    '''
    Class for listing IMAP folders with stats.
    '''

    def list(self, decode = True, unseen = True, recent = True, 
            messages = True):
        '''
        Lists all folders.
        '''
        typ, lst = self._imap.list()   
        if typ != 'OK':
            sys.stderr.write("list: %s\n" % str((typ, lst)))
            sys.exit(2)

        status = '('
        if unseen:
            status += 'UNSEEN '
        if recent:
            status += 'RECENT '
        if messages:
            status += 'MESSAGES '
        status = status.strip()
        status += ')'         


        for item in lst:
            if item.find('\\Noselect') != -1:
                continue
            vals = item.split('"')
            name = vals[-2]
            typ, val = self._imap.status(name, status)
            if typ != 'OK':
                sys.stderr.write("status[%s]: %s\n" % (name, str((typ, val))))
            else:
                if decode:
                    items = val[0].split('"')
                    print '"%s"%s' % (
                            unicode(items[1], 'imap4-utf-7'), 
                            items[2])
                else:
                    print val[0]

    def run(self, decode = True, unseen = True, recent = True, 
            messages = True):
        '''
        Executes all actions.
        '''
        self.login()
        self.list(decode, unseen, recent, messages)

def usage():
    '''
    Shows help.
    '''
    print '''
Usage: imap-stats [params]
Params:
 -h/--help          Shows this help.
 -v/--version       Shows version.
 -u/--no-unseen     Do not show unseen messages count.
 -r/--no-recent     Do not show recent messages count.
 -m/--no-messages   Do not show all messages count.
 -d/--no-decode     Show raw folder names.
'''

if __name__ == '__main__':
    DECODE = True
    UNSEEN = True
    RECENT = True
    MESSAGES = True

    try:
        OPTS, IGNORED = getopt.getopt(sys.argv[1:], 'hurmvd', [
            'help', 
            'version', 
            'no-RECENT', 
            'no-UNSEEN', 
            'no-MESSAGES', 
            'no-DECODE'])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    for opt, arg in OPTS:
        if opt in ('-h', '--help'):
            usage()
            sys.exit(0)
        if opt in ('-v', '--version'):
            print 'imap-stats version %s' % IMAPUtils.__version__
            sys.exit(0)
        if opt in ('-u', '--no-UNSEEN'):
            UNSEEN = False
        if opt in ('-r', '--no-RECENT'):
            RECENT = False
        if opt in ('-m', '--no-MESSAGES'):
            MESSAGES = False
        if opt in ('-d', '--no-DECODE'):
            DECODE = False

    ListIMAP().run(DECODE, UNSEEN, RECENT, MESSAGES)
