#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

version=`python -c 'import IMAPUtils; print IMAPUtils.__version__' | tr -d '\n'`

if [ "x$1" = "xbranch" ] ; then
    git tag -s -m "Tag release $version" $version
fi

./setup.py sdist --formats=gztar,bztar,zip

if [ "x$1" = "xbranch" ] ; then
    ./setup.py register
    ./setup.py sdist --formats=gztar,bztar,zip upload
    scp dist/imap-utils-$version.* web:/srv/http/dl.cihar.com/imap-utils/latest/
fi
